### ISSUE TITLE
subexpressions won't be executed properly

### ISSUE THREAD

**Issue by Marujah** [p-j/gulp-compile-handlebars#1]
getting an error when trying to use subexpressions

**Comment by VeronikaCavajdova** [comment]
@Marujah Hi, did you stop getting an error? It doesn't work for me either. If you fixed it, could you please post the solution? Thanks!

So, for the record, here was my problem:
1) the error when using subexpression syntax was on PhpStorm's side, it compiled properly
2) my template wasn't getting found, because i put ".hbs" to the path in data (yeah..)

Here's how I'm using it with Bootstrap tab content, if anyone wants to see it work:

tabs.hbs
```hbs
...
{{#each tabs}}
        <div role="tabpanel" class="tab-pane fade{{#if tabActive}} in active{{/if}}" id="{{tabId}}">
            {{> (lookup . 'tabContentUrl') }}
        </div>
{{/each}}
```

data.json
```json
{
  "tabs": [
    {"tabId": "dashboard", "tabTitle": "Dashboard", "tabContentUrl": "includes/index/dashboard", "tabActive": true},
    {"tabId": "calendar", "tabTitle": "Calendar", "tabContentUrl": "includes/index/calendar"}
  ]
}
```

**Comment by Marujah** [comment]
@VeronikaCavajdova Hello, I had another use case (I had js files contaning handlebars syntax)! my workaround was to save all th ejs files as .js.hbs and push them to the partials folder. I could then compile them
